db/seeds.rb

Create a Seed with 5 fake Users

Create seed with 5 users

---

app/controllers/products_controller.rb
config/routes.rb
test/controllers/products_controller_test.rb

Merci de valider pour partir avec le boilerplate complet :)

Productcontrollerindex

---

db/seeds.rb

Seed with 5 Users and Products

---

app/controllers/products_controller.rb
app/views/layouts/application.html.erb
app/views/products/index.html.erb

Products controller updated

---

app/controllers/application_controller.rb
app/views/devise/confirmations/new.html.erb
app/views/devise/mailer/confirmation_instructions.html.erb
app/views/devise/mailer/email_changed.html.erb
app/views/devise/mailer/password_change.html.erb
app/views/devise/mailer/reset_password_instructions.html.erb
app/views/devise/mailer/unlock_instructions.html.erb
app/views/devise/passwords/edit.html.erb
app/views/devise/passwords/new.html.erb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/devise/shared/_error_messages.html.erb
app/views/devise/shared/_links.html.erb
app/views/devise/unlocks/new.html.erb

updated sign-up with first_name AND last_name

---

app/assets/stylesheets/pages/_index.scss
app/assets/stylesheets/pages/_productindex.scss
app/views/products/index.html.erb

Please review my code folks :)

Product index front

---

app/views/layouts/application.html.erb
app/views/shared/_flashes.html.erb

Ajout d'un style plus sympa pour les alertes au login/logout

Modified  alert Devise in Layout

---

config/storage.yml

Finished config Cloudinary
ping @TheodorePRO

Add service Cloudinary in storage.yml

---

app/views/products/show.html.erb

slide show

---

app/controllers/application_controller.rb
app/controllers/products_controller.rb
app/policies/product_policy.rb
app/views/products/_form.html.erb
app/views/products/edit.html.erb
app/views/products/new.html.erb
app/views/products/show.html.erb

edit and update ProductController +
Edit button on show

Add Edit button in show and update logic

---

app/assets/stylesheets/components/_card_index.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/components/banner.scss
app/views/products/index.html.erb
app/views/shared/_navbar.html.erb

Please review my taf asap thank @Chabmax @pierre-bedouret

Front : Navbar + Banner + Search Bar + Card display grid

---

app/views/products/index.html.erb

lien unsplash random

---

app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb

Position du formulaire au centre de la page pour Login et Sign Up
ping @BrianRid

modify style for login and sign-up form

---

app/controllers/products_controller.rb
app/policies/product_policy.rb
app/views/products/show.html.erb

Product controller destroy

---

app/views/products/show.html.erb

La confirmation fonctionne maintenant

correction de are you sure

---

app/controllers/products_controller.rb

J'ai intégré l'autorisation directement dans set_product et rajouté un if/else dans update

modifyset_product and update in product_controller

---

app/javascript/components/init_sweetalert.js
app/javascript/packs/application.js
app/views/products/show.html.erb
package.json
yarn.lock

created sweet alert on delete product

---

app/views/products/_form.html.erb

Modify the width of the input.
Bigger and more responsive.

Form product

---

app/models/product.rb
app/views/products/_form.html.erb

modified product form

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/layouts/_index.scss
app/assets/stylesheets/layouts/_main.scss

reset margin et padding du body 
revu css des formulaires

add a general css for the layout

---

app/views/products/show.html.erb

juste des place holders pour les différents éléments de la show
Si vous êtes ok

revue de la show

---

app/views/products/index.html.erb
app/views/products/show.html.erb

Placeholder pour la map sur index

---

app/views/products/show.html.erb

Add button on show page

---

app/views/rentals/new.html.erb

pour pierre

---

app/controllers/rentals_controller.rb
app/policies/rental_policy.rb
test/policies/rental_policy_test.rb

Logic pour le controller => new 
+
Autorisation

created controller#new and Autorisation

---

app/assets/stylesheets/components/_card_show.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/pages/_index.scss
app/assets/stylesheets/pages/_productshow.scss
app/controllers/products_controller.rb
app/views/products/index.html.erb
app/views/products/show.html.erb

Je vous push ici la page Show product

page show product : Carousel + Card Proprio + card Product + card photos

---

app/assets/stylesheets/components/_carroussel.scss
app/assets/stylesheets/components/_index.scss
app/models/product.rb

solving pull request

---

app/controllers/rentals_controller.rb
app/views/products/_popup_rental.html.erb
app/views/products/show.html.erb
app/views/rentals/new.html.erb

Add popup to book a product directly in the show

---

app/assets/stylesheets/components/_card_index.scss

just little modification in css grid

add height=content to grid in order to fit card

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/pages/_dashboard.scss
app/controllers/pages_controller.rb
app/javascript/packs/application.js
app/views/pages/dashboard.html.erb

dashboard v3 enfin

---

app/javascript/components/filter.js
app/javascript/components/init_autocomplete.js
app/views/products/index.html.erb

finalisation des filtres

---

app/controllers/pages_controller.rb
app/models/user.rb
app/views/pages/dashboard.html.erb
db/seeds.rb

details dashboard

---

app/controllers/rentals_controller.rb
app/models/rental.rb

refacto validation car silent

---

app/controllers/pages_controller.rb
app/controllers/rentals_controller.rb
app/models/user.rb
app/policies/rental_policy.rb
app/views/pages/dashboard.html.erb

sur le dashboard, les totaux.
Manque un peu de SCSS à voir demain

avec les totaux de location

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/pages/_confirm.scss
app/assets/stylesheets/pages/_index.scss
app/controllers/rentals_controller.rb
app/models/rental.rb
app/policies/rental_policy.rb
app/views/rentals/confirm.html.erb
config/routes.rb

Create a corfirm page for a rental
